import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex bg-no-repeat bg-cover flex-col content-center items-center justify-center min-h-screen p-4 bg-[url('https://png.pngtree.com/background/20210715/original/pngtree-three-dimensional-gradient-e-commerce-promotion-background-picture-image_1322211.jpg')]">
            <img src="https://id.unica.vn/images/unica-w.png" alt="" className="z-10 mb-4 h-12 select-none"></img>
            {children}
        </div>
    );
}