import type { Metadata } from "next";

import LearningHeader from "@/components/LearningHeader";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LearingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <LearningHeader />
            {children}
        </>
    );
}