import React from "react";
import { Inter } from 'next/font/google';
import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';

import "@/styles/global.css";
import 'react-multi-carousel/lib/styles.css';
import 'react-phone-input-2/lib/style.css'

import LayoutProvider from "@/app/LayoutProvider";
import StoreProvider from "@/app/StoreProvider";

const inter = Inter({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Eduhub - Học online mọi kỹ năng từ các chuyên gia hàng đầu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <LayoutProvider>
            {children}
          </LayoutProvider>
          <Toaster />
        </StoreProvider>
      </body>
    </html>
  );
}
