import React from "react";
import { Inter } from 'next/font/google';
import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';

import "@/styles/global.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import LayoutProvider from "@/app/LayoutProvider";
import StoreProvider from "@/app/StoreProvider";

const inter = Inter({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <>
            <LayoutProvider>
              {children}
            </LayoutProvider>
            <Toaster position="top-right" />
          </>
        </StoreProvider>
      </body>
    </html>
  );
}
